import { ArrowUp, Mic, Search, X } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import type { FormEvent } from 'react'
import { readStored, removeStored, writeStored } from '../../utils/storage'

const recentSearchesKey = 'ditchgoogle-recent-searches'
const suggestions = ['Java tutorial', 'Java programming', 'How does quantum computing work?', 'Best Java frameworks', 'Latest cybersecurity research', 'React performance optimization', 'Privacy-first browsers']
type VoiceState = 'idle' | 'listening' | 'processing' | 'error'
type SpeechRecognitionLike = { start: () => void; onresult: ((event: { results: ArrayLike<ArrayLike<{ transcript: string }>> }) => void) | null; onend: (() => void) | null; onerror: (() => void) | null }

export function SearchBar({ initialQuery = '', onSubmit, large = false, autocompleteEnabled = true, voiceEnabled = true }: { initialQuery?: string; onSubmit: (query: string) => void; large?: boolean; autocompleteEnabled?: boolean; voiceEnabled?: boolean }) {
  const [query, setQuery] = useState(initialQuery)
  const [activeIndex, setActiveIndex] = useState(-1)
  const [voiceState, setVoiceState] = useState<VoiceState>('idle')
  const [focused, setFocused] = useState(false)
  const [recentSearches, setRecentSearches] = useState<string[]>(() => readStored(recentSearchesKey, []))
  const inputRef = useRef<HTMLInputElement>(null)
  const visibleSuggestions = focused && autocompleteEnabled ? (query.length >= 2 ? [...recentSearches, ...suggestions].filter((item, index, items) => items.indexOf(item) === index && item.toLowerCase().includes(query.toLowerCase())).slice(0, 6) : recentSearches.slice(0, 5)) : []
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); inputRef.current?.focus() } if (event.key === '/' && document.activeElement?.tagName !== 'INPUT') { event.preventDefault(); inputRef.current?.focus() } }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey) }, [])
  const recordSearch = (value: string) => { const next = [value, ...recentSearches.filter((item) => item !== value)].slice(0, 8); setRecentSearches(next); writeStored(recentSearchesKey, next); onSubmit(value) }
  const submit = (event: FormEvent) => { event.preventDefault(); const nextQuery = visibleSuggestions[activeIndex] || query.trim(); if (nextQuery) recordSearch(nextQuery) }
  const onInputKey = (event: React.KeyboardEvent<HTMLInputElement>) => { if (event.key === 'ArrowDown') { event.preventDefault(); setActiveIndex((value) => Math.min(value + 1, visibleSuggestions.length - 1)) } if (event.key === 'ArrowUp') { event.preventDefault(); setActiveIndex((value) => Math.max(value - 1, -1)) } if (event.key === 'Escape') { setActiveIndex(-1); setFocused(false) } if (event.key === 'Enter') { event.preventDefault(); const nextQuery = visibleSuggestions[activeIndex] || query.trim(); if (nextQuery) recordSearch(nextQuery) } }
  const startVoice = () => { const recognitionApi = window as Window & { SpeechRecognition?: new () => SpeechRecognitionLike; webkitSpeechRecognition?: new () => SpeechRecognitionLike }; const SpeechRecognition = recognitionApi.SpeechRecognition || recognitionApi.webkitSpeechRecognition; if (!SpeechRecognition) { setVoiceState('error'); window.setTimeout(() => setVoiceState('idle'), 1800); return } const recognition = new SpeechRecognition(); setVoiceState('listening'); recognition.onresult = (event) => { setVoiceState('processing'); setQuery(event.results[0][0].transcript); setFocused(false) }; recognition.onend = () => setVoiceState('idle'); recognition.onerror = () => { setVoiceState('error'); window.setTimeout(() => setVoiceState('idle'), 1800) }; try { recognition.start() } catch { setVoiceState('error') } }
  const clearHistory = () => { setRecentSearches([]); removeStored(recentSearchesKey) }
  const voiceLabel = voiceState === 'listening' ? 'Listening' : voiceState === 'processing' ? 'Processing voice search' : voiceState === 'error' ? 'Voice search unavailable' : 'Search by voice'
  return <div className="search-wrap"><form className={large ? 'search-form large' : 'search-form'} onSubmit={submit}><Search className="search-icon" size={large ? 21 : 18} /><input ref={inputRef} value={query} onFocus={() => setFocused(true)} onBlur={() => window.setTimeout(() => setFocused(false), 100) } onChange={(event) => { setQuery(event.target.value); setActiveIndex(-1) }} onKeyDown={onInputKey} placeholder="Search the web privately..." aria-label="Search the web" aria-autocomplete="list" aria-controls="search-suggestions" />{query && <button type="button" className="clear-search" onClick={() => setQuery('')} aria-label="Clear search"><X size={16} /></button>}{voiceEnabled && <button type="button" className={voiceState === 'listening' ? 'voice-search listening' : 'voice-search'} onClick={startVoice} aria-label={voiceLabel}><Mic size={16} /></button>}<kbd>/</kbd><button className="submit-search" type="submit" aria-label="Search"><ArrowUp size={18} /></button></form>{voiceState !== 'idle' && <div className="voice-status">{voiceState === 'error' ? 'Voice search is unavailable in this browser' : `${voiceState[0].toUpperCase()}${voiceState.slice(1)}...`}</div>}{visibleSuggestions.length > 0 && <div className="autocomplete" id="search-suggestions" role="listbox">{visibleSuggestions.map((item, index) => <button className={index === activeIndex ? 'autocomplete-item active' : 'autocomplete-item'} key={item} role="option" aria-selected={index === activeIndex} onMouseDown={() => recordSearch(item)}><Search size={14} /><span>{highlight(item, query)}</span></button>)}{query.length === 0 && <button className="autocomplete-clear" onMouseDown={(event) => event.preventDefault()} onClick={clearHistory}>Clear recent searches</button>}</div>}</div>
}

function highlight(value: string, query: string) { const index = value.toLowerCase().indexOf(query.toLowerCase()); if (index < 0) return value; return <>{value.slice(0, index)}<strong>{value.slice(index, index + query.length)}</strong>{value.slice(index + query.length)}</> }
